### ISSUE TITLE
IDE Internal Error Prompt every 10 minutes

### ISSUE THREAD

**Issue by tuminzee** [ton-blockchain/intellij-ton#132]
This error prompts up every 10 minutes

<img width="936" alt="image" src="https://github.com/ton-blockchain/intellij-ton/assets/58180803/cd59a59f-7890-4a24-ba99-07502f05aed8">

**Environment Configuration**
WebStorm 2023.2.1
Build #WS-232.9559.58, built on August 22, 2023
Runtime version: 17.0.8+7-b1000.8 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.andreypfau.intellij-ton (2.0.1)

**Error in text**
`com.intellij.util.indexing.impl.MapReduceIndexMappingException: java.lang.NullPointerException: Can't find stub index extension for key 'func.all.name'
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:229)
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:181)
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:147)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:30)
	at com.intellij.util.indexing.SingleEntryIndexer.map(SingleEntryIndexer.java:19)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.preciseCheck(PerFileElementTypeStubModificationTracker.java:164)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.lambda$endUpdatesBatch$2(PerFileElementTypeStubModificationTracker.java:97)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:923)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:63)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.endUpdatesBatch(PerFileElementTypeStubModificationTracker.java:91)
	at com.intellij.util.indexing.events.ChangedFilesCollector$4.endBatch(ChangedFilesCollector.java:252)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$endBatch$2(ChangedFilesCollector.java:289)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:264)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.endBatch(ChangedFilesCollector.java:288)
	at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:109)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:271)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:230)
	at com.intellij.util.indexing.events.ChangedFilesCollector.ensureUpToDate(ChangedFilesCollector.java:191)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:785)
	at com.intellij.util.indexing.FileBasedIndexEx.ensureUpToDate(FileBasedIndexEx.java:541)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:164)
	at com.intellij.psi.stubs.StubIndex.processElements(StubIndex.java:53)
	at com.intellij.lang.javascript.psi.util.JSStubBasedPsiTreeUtil.processElementsForFile(JSStubBasedPsiTreeUtil.java:1071)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptQualifiedNameResolver.getLocalClassesForName(TypeScriptQualifiedNameResolver.java:312)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptImportHandler.resolveNameImpl(TypeScriptImportHandler.java:133)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptImportHandler.resolveNameImpl(TypeScriptImportHandler.java:91)
	at com.intellij.lang.javascript.ecmascript6.TypeScriptImportHandler.resolveTypeName(TypeScriptImportHandler.java:74)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSReferenceListImpl.resolveTextReferenceClasses(JSReferenceListImpl.java:137)
	at com.intellij.lang.javascript.psi.ecmal4.impl.JSReferenceListImpl.resolveMemberClasses(JSReferenceListImpl.java:190)
	at com.intellij.lang.javascript.psi.ecma6.impl.JSReferenceListMemberImpl.getClassesWithSubstitutors(JSReferenceListMemberImpl.java:105)
	at com.intellij.lang.javascript.psi.util.JSClassHierarchyVisitor.visitSuperReference(JSClassHierarchyVisitor.java:123)
	at com.intellij.lang.javascript.psi.util.JSClassHierarchyVisitor.processRefs(JSClassHierarchyVisitor.java:110)
	at com.intellij.lang.javascript.psi.util.JSClassHierarchyVisitor.visit(JSClassHierarchyVisitor.java:96)
	at com.intellij.lang.javascript.psi.util.JSClassHierarchyVisitor.visit(JSClassHierarchyVisitor.java:60)
	at com.intellij.lang.javascript.psi.util.JSClassUtils.processClassesInHierarchyImpl(JSClassUtils.java:162)
	at com.intellij.lang.javascript.psi.util.JSClassUtils.processClassesInHierarchy(JSClassUtils.java:152)
	at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptClassBase.processSupers(TypeScriptClassBase.java:163)
	at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptClassBase.processDeclarations(TypeScriptClassBase.java:137)
	at com.intellij.lang.javascript.psi.resolve.AccessibilityProcessingHandler.computeAcceptProtected(AccessibilityProcessingHandler.java:304)
	at com.intellij.lang.javascript.psi.resolve.AccessibilityProcessingHandler.startingParent(AccessibilityProcessingHandler.java:278)
	at com.intellij.lang.javascript.psi.resolve.ResolveProcessor.startingParent(ResolveProcessor.java:154)
	at com.intellij.lang.javascript.psi.resolve.SinkResolveProcessor.startingParent(SinkResolveProcessor.java:229)
	at com.intellij.lang.javascript.psi.resolve.ResolveProcessor.handleEvent(ResolveProcessor.java:142)
	at com.intellij.lang.javascript.psi.resolve.SinkResolveProcessor.handleEvent(SinkResolveProcessor.java:274)
	at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptClassBase.processDeclarations(TypeScriptClassBase.java:99)
	at com.intellij.lang.javascript.psi.resolve.JSCollectMembersToImplementProcessor.execute(JSCollectMembersToImplementProcessor.java:57)
	at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptClassBase.processTypeAndTypeParameters(TypeScriptClassBase.java:305)
	at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptClassBase.processDeclarations(TypeScriptClassBase.java:92)
	at com.intellij.lang.javascript.psi.resolve.JSResolveUtil.processInterfaceMembers(JSResolveUtil.java:152)
	at com.intellij.lang.javascript.psi.resolve.JSInheritanceUtil.findImplementedMembers(JSInheritanceUtil.java:163)
	at com.intellij.lang.javascript.inspections.unusedsymbols.JSUnusedSymbolsVisitor.checkUnused(JSUnusedSymbolsVisitor.java:197)
	at com.intellij.lang.javascript.inspections.unusedsymbols.JSUnusedSymbolsVisitor.visitJSFunctionDeclaration(JSUnusedSymbolsVisitor.java:98)
	at com.intellij.lang.javascript.psi.ecma6.impl.TypeScriptFunctionImpl.accept(TypeScriptFunctionImpl.java:55)
	at com.intellij.lang.javascript.inspections.unusedsymbols.JSUnusedGlobalSymbolsPass.searchForUnusedSymbols(JSUnusedGlobalSymbolsPass.java:141)
	at com.intellij.lang.javascript.inspections.unusedsymbols.JSUnusedGlobalSymbolsPass.doCollectInformation(JSUnusedGlobalSymbolsPass.java:89)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:390)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:77)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:24)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:386)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:377)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:376)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:352)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:207)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:350)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NullPointerException: Can't find stub index extension for key 'func.all.name'
	at com.intellij.psi.stubs.StubIndexKeyDescriptorCache.findExtension(StubIndexKeyDescriptorCache.kt:51)
	at com.intellij.psi.stubs.StubIndexKeyDescriptorCache.access$findExtension(StubIndexKeyDescriptorCache.kt:13)
	at com.intellij.psi.stubs.StubIndexKeyDescriptorCache$getOrCache$1.invoke(StubIndexKeyDescriptorCache.kt:33)
	at com.intellij.psi.stubs.StubIndexKeyDescriptorCache$getOrCache$1.invoke(StubIndexKeyDescriptorCache.kt:32)
	at com.intellij.psi.stubs.StubIndexKeyDescriptorCache.getOrCache$lambda$0(StubIndexKeyDescriptorCache.kt:32)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.psi.stubs.StubIndexKeyDescriptorCache.getOrCache(StubIndexKeyDescriptorCache.kt:32)
	at com.intellij.psi.stubs.StubIndexKeyDescriptorCache.getKeyHashingStrategy(StubIndexKeyDescriptorCache.kt:19)
	at com.intellij.psi.stubs.SerializedStubTree.lambda$indexTree$0(SerializedStubTree.java:192)
	at com.intellij.psi.stubs.ObjectStubTree$StubIndexSink.occurrence(ObjectStubTree.java:116)
	at org.ton.intellij.func.stub.type.FuncFunctionStubElementType.indexStub(FuncFunctionStubElementType.kt:47)
	at org.ton.intellij.func.stub.type.FuncFunctionStubElementType.indexStub(FuncFunctionStubElementType.kt:14)
	at com.intellij.psi.stubs.ObjectStubTree.indexStubTree(ObjectStubTree.java:57)
	at com.intellij.psi.stubs.SerializedStubTree.indexTree(SerializedStubTree.java:190)
	at com.intellij.psi.stubs.SerializedStubTree.serializeStub(SerializedStubTree.java:60)
	at com.intellij.psi.stubs.StubUpdatingIndex$2.computeValue(StubUpdatingIndex.java:218)
	... 79 more
`

**Comment by stels-cs** [comment]
Same problem after update from v1 to v2

**Comment by andreypfau** [comment]
Use latest version:
https://github.com/ton-blockchain/intellij-ton/releases/tag/v2.0.2

It still on moderation in JetBrains Marketplace, its will avaliable soon
